//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validacoes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Validacoes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClinicaMedica.Resources.Validacoes", typeof(Validacoes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar o atendente responsável por agendar a consulta.
        /// </summary>
        public static string AvisoAtendenteVazio {
            get {
                return ResourceManager.GetString("AvisoAtendenteVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Só é possível cancelar uma consulta que está agendada.
        /// </summary>
        public static string AvisoCancelarConsultaComStatusDiferenteDeAgendado {
            get {
                return ResourceManager.GetString("AvisoCancelarConsultaComStatusDiferenteDeAgendado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar ao menos um sintoma do paciente.
        /// </summary>
        public static string AvisoConsultaSemSintomas {
            get {
                return ResourceManager.GetString("AvisoConsultaSemSintomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido agendar consultas com datas retrogradas.
        /// </summary>
        public static string AvisoDataRetrograda {
            get {
                return ResourceManager.GetString("AvisoDataRetrograda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Só é possível finalizar uma consulta que está em progresso.
        /// </summary>
        public static string AvisoFinalizarConsultaComStatusDiferenteDeEmProgresso {
            get {
                return ResourceManager.GetString("AvisoFinalizarConsultaComStatusDiferenteDeEmProgresso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível iniciar uma consulta que não está agendada para hoje.
        /// </summary>
        public static string AvisoIniciarConsultaComStatusDiferenteDeAgendado {
            get {
                return ResourceManager.GetString("AvisoIniciarConsultaComStatusDiferenteDeAgendado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médico e paciente são obrigatórios.
        /// </summary>
        public static string AvisoMedicoPacienteVazio {
            get {
                return ResourceManager.GetString("AvisoMedicoPacienteVazio", resourceCulture);
            }
        }
    }
}
